/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    transitionDuration: {
      DEFAULT: "300ms",
      100: "100ms",
      200: "200ms",
      300: "300ms",
    },
    container: {
      center: true,
      maxWidth: "1230px",
      padding: {
        DEFAULT: "20px",
        lg: "30px",
      },
      screens: {
        sm: "600px",
        md: "728px",
        lg: "984px",
        xl: "1240px",
      },
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1230px",
      "2xl": "1480px",
    },
    fontSize: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "2.125rem",
      "4xl": "2.875rem",
      "5xl": "3.75rem",
      "6xl": "4.5rem",
      "7xl": "5rem",
    },
    lineHeight: {
      none: "1",
      xs: "1.16",
      sm: "1.32",
      md: "1.48",
      lg: "1.64",
      lx: "1.82",
      double: "2",
    },
    borderRadius: {
      none: "0",
      xs: "2px",
      sm: "5px",
      DEFAULT: "8px",
      md: "10px",
      lg: "24px",
      full: "9999px",
    },
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#fff",
      whiteHover: "#ececec",
      black: "#222222",
      pink: "#FFA3A3",
      red: "#FC5252",
      redHover: "#ff6565",
      blue: "#381DDB",
    },
    fontFamily: {
      sans: ["Raleway, sans-serif"],
      headline: ["Montserrat, sans-serif"],
      localSans: ["sans-serif"],
    },
    extend: {},
  },
  plugins: [],
};
